# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-15 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_auto_20181115_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='like',
            name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_quotes', to='belt_app.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
